### ISSUE TITLE
Side tabs doesn't appear

### ISSUE THREAD

**Issue by yoshiakis** [prisma/graphql-playground#1000]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What is the expected behavior?
Select a settings tab and then a GraphQL editor tab. After that, side tabs should appear.

#### What is the actual behavior?
Side tabs doesn't appear.

#### What steps may we take to reproduce the behavior?
- Enable schema polling.
- Make sure introspection query succeeds.
- Select a GraphQL editor tab and then a settings tab and then the same GraphQL editor tab again. The endpoint in the URL bar in the GraphQL editor tab needs to be the same as the one entered when opening GraphQL Playground.

_Please provide a gif or image of the issue for a quicker response/fix._
![SideTabsDoesntAppear](https://user-images.githubusercontent.com/7870808/55290468-9eae2900-540e-11e9-8fc1-cb8db7f83dd6.gif)

**Comment by mattc41190** [comment]
I am seeing this as well.
