### ISSUE TITLE
Playground frontend is double json encoding results

### ISSUE THREAD

**Issue by halkeye** [prisma/graphql-playground#1008]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [X] GraphQL Playground HTML
- [X] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

Windows 10, Firefox 66.0.2 (64-bit)

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js

(i'm guessing latest, happens on graphiql too)

#### What is the expected behavior?

Response body is json

#### What is the actual behavior?

Response body is stringified json

#### What steps may we take to reproduce the behavior?

You might need my jenkins plugin to truely reproduce it, i'm not sure if its backend for frontend or some missing header or something.

Redux:
```
{
  type: 'SET_RESPONSE',
  payload: {
    workspaceId: 'https://4r27q9ljl9.sse.codesandbox.io/',
    sessionId: 'cju7ribc50000266318iw2c48',
    response: {
      resultID: 'cju7vlvvo00012663le8wbq97',
      date: '{\n  "data": {\n    "widgets": [\n      {\n        "id": "1",\n        "name": "Foo",\n        "type": {\n          "__typename": "C",\n          "baz": "Baz"\n        },\n        "description": ""\n      }\n    ]\n  }\n}',
      time: '2019-04-08T04:49:00.324Z'
    }
  }
}
```

Node command line (works)"
```
const fetch = require("node-fetch");
const ApolloClient = require('apollo-boost').default;
const gql = require('graphql-tag');

const client = new ApolloClient({
    uri: "http://localhost:8080/jenkins/graphql/",
    fetch: fetch
});

client.query({ query: gql`query { allJobs { name } }` })
  .then(data => console.log(JSON.stringify(data, null, 4)))
  .catch(error => console.error(error));%    
```

Response:
```
{
    "data": {
        "allJobs": [
            {
                "name": "testfreestyle",
                "__typename": "FreeStyleProject"
            }
        ]
    },
    "loading": false,
    "networkStatus": 7,
    "stale": false
}
```

**Comment by halkeye** [comment]
Har files:
https://gist.github.com/halkeye/0a11d6aaf187d66a2cbc0ef53db6745e

**Comment by halkeye** [comment]
I think its before graphql-playground, I think its apollo, but i'm not certain enough to know how/what libraries are used to open a bug somewhere else.

**Comment by yoshiakis** [comment]
Thank you for raising an issue! I'm afraid I don't fully understand what's been happened. Could you show an error log or a screenshot which shows what's happening or something like that?

**Comment by halkeye** [comment]
https://i.imgur.com/l2Ojt7A.png

Desktop client (both graphql-playground, and graphiql) work, but embedded JS versions seem to double encode. 

Embedded code is - https://github.com/halkeye/graphql-server-plugin/blob/master/src/main/webapp/js/playground.js and https://github.com/halkeye/graphql-server-plugin/blob/master/src/main/resources/io/jenkins/plugins/io/jenkins/plugins/graphql/RootAction/playground.jelly

As far as I can tell its outputting the right thing (and desktop clients work) but I'm at a loss. The har file can provide more details. My only theory is that its possibly because jenkins auto adds a no-sniff header.

**Comment by yoshiakis** [comment]
Would you show me the har file as well?

**Comment by halkeye** [comment]
Yea if you give me a private way to contact you I can also give you a url and credentials to access the instance.

**Comment by halkeye** [comment]
![image](https://user-images.githubusercontent.com/110087/58374491-dd82cb80-7ef3-11e9-9739-4fbb42c500aa.png)

[Archive 19-05-25 13-48-11.zip](https://github.com/prisma/graphql-playground/files/3219735/Archive.19-05-25.13-48-11.zip)

**Comment by yoshiakis** [comment]
Thanks! Do you have the same problem when you send the query via [the demo page](https://graphqlbin.com)?

**Comment by halkeye** [comment]
Works fine via the demo page. Took a bit of time to get CORS working.

Even after cors was implemented, tried it using it inside my plugin with both my public https domain (cross domain), and the localhost domain (non cross domain).  and still breaks.

**Comment by yoshiakis** [comment]
I've read the har file and It looks to me that you've got the correct form of response.content.text. You said it worked fine via the demo page. I'm not sure but I'm thinking Jenkins is maybe doing something wrong which changes response.content.text.

Could you please check if it works when you use `cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js` without using Jenkins at client side? (You may use Jenkins at API server side.)

**Comment by halkeye** [comment]
oh! like loading prototype.js or something.

Okay, i'll try to do that tomorrow

**Comment by halkeye** [comment]
Actually I figured out how to just not include all the extra jenkins header/footers and it seemed to work.

Since this is mostly for a debugging tool (in this instance) and not meant for day to day use, I might just leave it like that.

I suspect it has something todo with prototypejs breaking things (it breaks a lot of the internet these days). Probably related to https://github.com/jenkinsci/jenkins/blob/75468da366c1d257a51655dcbe952d55b8aeeb9c/war/src/main/js/util/jenkins.js#L23-L57

I'll happily help dig into whats causing it if you want to provide more tips, but otherwise i'm good to close this.

**Comment by yoshiakis** [comment]
Please close this issue :)

btw, as you've may noticed, I think extra jenkins header/footers converts JSONArrays in response.content.text to JSONStrings.
