### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by MissLlq** [prisma/graphql-playground#1013]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ y] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

10.13.6
#### What is the expected behavior?

screen show nothing
#### What steps may we take to reproduce the behavior?

_Please provide a gif or image of the issue for a quicker response/fix._

**Cannot read property 'get' of undefined**

**Comment by yoshiakis** [comment]
Hi @MissLlq! Would you provide the way how to reproduce this behavior more specifically? Maybe I understand what's the cause.

**Comment by yoshiakis** [comment]
@MissLlq 
Please reopen this issue if you are still experiencing it.

**Comment by Fabiomad85** [comment]
I still experice this problem on https://app.prisma.io/

**Comment by Fabiomad85** [comment]
> I still experice this problem on https://app.prisma.io/

I had the problem on Chrome, on firefox it works
