### ISSUE TITLE
Playground not loading with Express Middleware throwing 404

### ISSUE THREAD

**Issue by emlyknguyen** [prisma/graphql-playground#1036]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [x] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac HighSierra 10.13.6

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
graphql-playground-middleware-express 1.7.12

#### What is the expected behavior?
The package imported is 1.7.12

#### What is the actual behavior?
It is trying to access graphql-playground-react@1.7.26 and throwing a 404

#### What steps may we take to reproduce the behavior?

_Please provide a gif or image of the issue for a quicker response/fix._
<img width="919" alt="Screen Shot 2019-06-10 at 10 41 52 PM" src="https://user-images.githubusercontent.com/13125556/59246374-ffa56a80-8bd0-11e9-9a55-8ee70c277c32.png">

**Comment by yoshiakis** [comment]
Hi @emlyknguyen, I need more information to understand why Playground is trying to access to the version of 1.7.26. Could you tell me what config object you've pass into GraphQL Playground Express Middleware?

**Comment by iszfan** [comment]
Hi @yoshiakis, thank you for the response! Emily and I are running the same code. I have been able to access https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.10/build/static/js/middleware.js. While she is providing you with the config object, is there any reason why the same code could access different version of graphql-playground-react?

**Comment by emlyknguyen** [comment]
Hi @yoshiakis! I ran it just now and it suddenly works again. The issue was happening intermittently yesterday...here is the config object for the playground.
`const playground = expressPlayground({
  ...defaultPlaygroundOptions,
  endpoint: `/graphql?headers=${encodeURIComponent(authorizationHeader)}`,
  settings: {
    ...defaultPlaygroundOptions.settings,
    'request.credentials': 'include'
  }
});`

**Comment by yoshiakis** [comment]
Hi @iszfan and @emlyknguyen, you can select which version of graphql-playground-react you get from CDN by passing `version` property into expressPlayground. For instance, You want to use the version of 1.7.10 of graphql-playground-react, you need to set config object into expressPlayground like so:
```js
const playground = expressPlayground({ version: '1.7.10' });
```

If you doesn't pass version property into expressPlayground, it gets the latest version from CDN.

So now my question is what exactly `defaultPlaygroundOptions` is which you showed above?

**Comment by KamalAman** [comment]
Experiencing the same issue with this `1.7.12` is trying to access `https://cdn.jsdelivr.net/npm/graphql-playground-react@1.7.26`

The defaultPlaygroundOptions in my case are coming from apollo-server-express

```js
const { ApolloServer, defaultPlaygroundOptions } = require('apollo-server-express');
``` 

```json
{
  "version": "1.7.26",
  "settings": {
    "general.betaUpdates": false,
    "editor.theme": "dark",
    "editor.cursorShape": "line",
    "editor.reuseHeaders": true,
    "tracing.hideTracingResponse": true,
    "queryPlan.hideQueryPlanResponse": true,
    "editor.fontSize": 14,
    "editor.fontFamily": "'Source Code Pro', 'Consolas', 'Inconsolata', 'Droid Sans Mono', 'Monaco', monospace",
    "request.credentials": "omit"
  }
}
```

My apollo-server-express is 2.6.2, so really this is an issue with the options that apollo-server-express exports.

**Comment by yoshiakis** [comment]
Hi @KamalAman!
> why did this work in the first place?

I would think it's because `defaultPlaygroundOptions` has had `1.7.10` as `version` property before.

> version: 1.7.12 does not work

Because GrpahQL Playground react doesn't have the version of `1.7.12`

**Comment by yoshiakis** [comment]
@emlyknguyen and @iszfan, I'm going to close this issue. If you have the same issue again please let me know so that I can reopen this issue.

**Comment by iszfan** [comment]
Hi @yoshiakis, we are seeing this issue pretty consistently now. For the defaultPlaygroundOptions, we are getting it from 'apollo-server-express'

**Comment by yoshiakis** [comment]
Hi @iszfan, I don't think it's the bug of `graphql-playground` but of `apollo-server-express`.

**Comment by iszfan** [comment]
Thank you @yoshiakis , it is specfied in `apollo-server-express` [here](https://github.com/apollographql/apollo-server/blob/42ab6b86b7fb3adcdb5f3fd1036cfa2b7a524803/packages/apollo-server-core/src/playground.ts#L13) Will open an issue there.

**Comment by cleverplatypus** [comment]
The new versions of `graphql-playground-react` seem to be under `@apollographql/graphql-playground-react` but the jsDelivr url is hard-coded in `graphql-playground-html` without the prefix. 

Should this be fixed?
