### ISSUE TITLE
NPM Install Failing

### ISSUE THREAD

**Issue by acinader** [prisma/graphql-playground#1052]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?

OSX 10.14.5

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.7.20

#### What is the expected behavior?

npm install should work

#### What is the actual behavior?

npm install errors with: 
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/graphql-playground-react/codemirror-graphql@github:timsuchanek/codemirror-graphql#801ec32683c38d6dc0f8f7bc19014a111edc9ebd" as it does not contain a package.json file.
```
#### What steps may we take to reproduce the behavior?

My package.json looks like this:

```  "graphql-playground-react": "^1.7.20",```

**Comment by acinader** [comment]
Issue was my package-lock.json.  All good now  😬

**Comment by labmux** [comment]
@acinader Can you elaborate? Im having the same issue

**Comment by alljinx** [comment]
> @acinader Can you elaborate? Im having the same issue

Same here...
