### ISSUE TITLE
Execute a query multiple times through a loop

### ISSUE THREAD

**Issue by LaurenceM10** [prisma/graphql-playground#1057]
Is there a way to execute a query multiple times through a loop?
For example: 
<img width="896" alt="Screen Shot 2019-07-15 at 3 25 27 PM" src="https://user-images.githubusercontent.com/13529689/61250534-2fd2b280-a715-11e9-9946-11178602b368.png">

**Comment by httpiago** [comment]
No, this is not possible because this is not a valid syntax in the GraphQL specification, if you want this you will have to do it outside the graphql-playground.

**Comment by LaurenceM10** [comment]
I know it's not part of the graphql syntax, I was asking it for test purposes.

Sometimes I want to do 100-200 test request of the same query.

**Comment by huv1k** [comment]
You can write integration tests for it. Closing this because it's not issue.
