### ISSUE TITLE
GraphQL Playground crashing because of accidentally typed non-breaking space

### ISSUE THREAD

**Issue by pnguyen9** [prisma/graphql-playground#1068]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Ubuntu 18.04.3 LTS

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.30

#### What is the expected behavior?
Should not crash. 

#### What is the actual behavior?
Whenever you're typing your queries/mutations, if you type too fast, you might accidentally write a non-breaking space by pressing Alt Gr + Space without knowing it, which gives the following character: 

#### What steps may we take to reproduce the behavior?
- Open a GraphQL playground (any will do), preferably in private browsing. 
- Start writing a query with brackets, then write a non-breaking space by pressing Alt Gr + Space. 
- If you try to write or do anything without removing the non-breaking space, the active tab will soon crash (if the non-breaking space was written right before an opening bracket; otherwise, the tab will only behave in an odd way). 
- If you refresh the page, the entire playground will crash and you'll have to clear your local storage, and you'll now have to rewrite all your queries from the beginning. 

_Please provide a gif or image of the issue for a quicker response/fix._

Active tab crashing:
![image](https://user-images.githubusercontent.com/22443655/62794880-2e569900-bacd-11e9-8897-f2aab49f006c.png)

Entire playground crashing after refreshing:
![image](https://user-images.githubusercontent.com/22443655/62794950-5e9e3780-bacd-11e9-8113-dac925b44f2e.png)

**Comment by robinmetral** [comment]
This is a known GraphiQL issue (see https://github.com/graphql/graphiql/issues/735), which has been fixed a few days ago in `graphiql@0.14.0`.

Upgrading the GraphiQL dependency should be enough to fix this :arrow_right: #1071 

:slightly_smiling_face:
