### ISSUE TITLE
Subscription Authorization Using JWT Token

### ISSUE THREAD

**Issue by kmanev073** [prisma/graphql-playground#1075]
I am having some subscriptions in my project but I can't test them through the Playground because I have some authorization policies. I think I can't send send my authorization token. I tried setting the http headers but this didn't work. Is there anything else I could try to do or I have to disable the authentication/authorization in my development branch?

**Comment by adamgarcia4** [comment]
Please look at the connection parameter passed into the context function:

![image](https://user-images.githubusercontent.com/7979621/63751782-ae944100-c8b8-11e9-96e4-39c2137ae561.png)
