### ISSUE TITLE
Flatpac build

### ISSUE THREAD

**Issue by utx0** [prisma/graphql-playground#1400]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?

I am on fedora. 

Please if possible provide a flatpac build of the app. This would be super handy for none snap or deb based linux systems to then have support via flatpac. ie fedora/redhat.

**Comment by mlncn** [comment]
Is this a duplicate of #729 ?

**Comment by utx0** [comment]
yep, closing.
