### ISSUE TITLE
Shared playground id's not case-sensitive

### ISSUE THREAD

**Issue by kbrandwijk** [prisma/graphql-playground#184]
The generated playground id's are not case-sensitive.

**Comment by timsuchanek** [comment]
@kbrandwijk what do you mean with that? That the case will be ignored in the graphql-bin?

**Comment by kbrandwijk** [comment]
@timsuchanek Yes. When you share, you get an url with lowercase and UPPERCASE characters, but you can also access using any casing. For example, I just shared and empty one and got https://graphqlbin.com/j0McG. But https://graphqlbin.com/j0mcg (or https://graphqlbin.com/J0MCG) also works, so that makes it a lot less random.

**Comment by Huvik** [comment]
Now it works correctly, thanks for reporting issue.
