### ISSUE TITLE
Replace styled-jsx with styled-components

### ISSUE THREAD

**Issue by schickling** [prisma/graphql-playground#200]
`styled-jsx` introduces a lot of build-time complexity. Would be great if it could be replaced with `styled-components`.

**Comment by steida** [comment]
Just curious which complexity? styled-components are by my observation much leaky abstraction.

**Comment by schickling** [comment]
The current build-setup is very complicated and involves multiple forked packages (and is currently hard to get locally set up). To make it easier for new developers to contribute to graphql-playground the build setup should be a simple as possible.

**Comment by morajabi** [comment]
I'd like to to this!

**Comment by schickling** [comment]
This will involve a fair amount of work @morajabi but this would be absolutely great!
