### ISSUE TITLE
make it possible to download the schema

### ISSUE THREAD

**Issue by timsuchanek** [prisma/graphql-playground#25]
In either json or sdl format

**Comment by kuldar** [comment]
Proposed design for downloading JSON/SDL format of the Schema from sidebar drawer.

![schema](https://user-images.githubusercontent.com/1710629/48949835-a37f3f80-ef39-11e8-888d-e4144b211786.png)
![dropdown](https://user-images.githubusercontent.com/1710629/48949834-a37f3f80-ef39-11e8-8300-d4477e186c6f.png)
