### ISSUE TITLE
[bug] subscriptionEndpoint ignored on graphql-playground-middleware-koa@>=1.3.5

### ISSUE THREAD

**Issue by amitport** [prisma/graphql-playground#358]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [X] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
window + linux

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
graphql-playground-middleware-koa  1.3.5 and 1.3.6,

#### What is the expected behavior?
`subscriptionEndpoint: '/subscriptions'` should cause the server to connect to the specific path

#### What is the actual behavior?
server tries to connect to websocket on path `graphql` (regular endpoint)

(note this worked fine with `graphql-playground-middleware-koa@1.3.1`)

**Comment by amitport** [comment]
possibly related to https://github.com/graphcool/graphql-playground/issues/220

**Comment by Huvik** [comment]
It should be fixed, if its still problem please reopen the issue.
