### ISSUE TITLE
Provide initial context (tabs, queries, headers, variables)

### ISSUE THREAD

**Issue by schickling** [prisma/graphql-playground#487]
When using the `graphql-playground-react` component (or also via e.g. `graphql-yoga`) it's a common scenario that you'd want to preconfigure a query or provide other context information.

**Comment by kbrandwijk** [comment]
Already tracked here: https://github.com/graphcool/graphql-playground/issues/301

**Comment by schickling** [comment]
I think it's an important enough feature to be tracked on its own. Also, I couldn't find it via search.

**Comment by notrab** [comment]
I'd really like to see this happen. Perhaps this is easier to get through than all in #301 ?

What are your thoughts? I can submit a PR if anyone can point me in the right direction to implement this too if I can get some spare time.

**Comment by notrab** [comment]
Any update on this @timsuchanek ? Excited to see this support land if anyone is currently working on it.

**Comment by Huvik** [comment]
Its already done few versions back.
