### ISSUE TITLE
Add query parameters to middleware pages

### ISSUE THREAD

**Issue by lorensr** [prisma/graphql-playground#578]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground Express Middleware

It would be nice to be able to link to a Playground like this:

`http://api.foo.com/playground?query={me{name}}`

to set the `query` (like you can in GraphiQL) and maybe other fields, like endpoint and headers.

**Comment by Huvik** [comment]
Its possible to pass it like props of the playground or in the query string.

**Comment by jgillich** [comment]
@Huvik I looked through the source and I don't think there's any way to set the query via props. Are you sure about this? GraphQL If no, I'd suggest this to be reopened.

**Comment by Huvik** [comment]
@jgillich Its possible to do that, you can check how yoga is doing it https://github.com/prisma/graphql-yoga/commit/c9f10c4adf65b5aa7b9a1262129bf2e684068052#diff-f41e9d04a45c83f3b6f6e630f10117feR339

**Comment by jgillich** [comment]
Oh darn, it's part of tabs? Thank you, that works!
