### ISSUE TITLE
Automatic update of npm package

### ISSUE THREAD

**Issue by hailwood** [prisma/graphql-playground#612]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

As per #590 there is an npm published version of graphql-playground, however it is significantly out of date. There was a request to update this, I am proposing that we introduce an automated step that will publish a new release each time a release it tagged in github so we don't have to ask for a less outdated version again in six months.

**Comment by hailwood** [comment]
@timsuchanek

**Comment by Huvik** [comment]
This is already fixed. Sorry for problems.
