### ISSUE TITLE
Proposal: Default headers for GraphQLPlayground.init

### ISSUE THREAD

**Issue by RStankov** [prisma/graphql-playground#636]
I'm building a Ruby on Rails integration for GraphQL Playground - [here](https://github.com/RStankov/graphql-playground-rails).

In a lot of Ruby on Rails application, developers use the `GraphQL` with the build in [CSRF protection](http://guides.rubyonrails.org/security.html#csrf-countermeasures). 

For the gem to work, I have to be able to set default headers for the GraphQL endpoint. I imagining the following would do the trick:

```js
window.addEventListener('load', function (event) {
  GraphQLPlayground.init(document.getElementById('root'), {
    endpoint: '<%= graphql_endpoint_path %>',
    headers: {
      'X-CSRF-Token': '<%= form_authenticity_token %>',
    },
  });
});
 
```

This would also be useful, for default authentication headers and similar.

**Comment by robertopedroso** [comment]
Seconding this -- I was working on a PR to add `graphql-playground` as an optional interface to [graphene-django](https://github.com/graphql-python/graphene-django), but the inability to set headers through the playground's `init` function makes this impossible.

The `<Playground />` component accepts `headers` as an optional prop. I'm pretty sure the prop would simply have to be added to `<PlaygroundWrapper />` and `<GraphQLBinApp />`.

I lack React expertise, but if someone can confirm my thoughts on passing this prop down, I'd be happy to make a PR.

**Comment by daemonsy** [comment]
This is an awesome feature, just adding a little opinion about potential use case I have for this. 

Developing a graphql API for one of our API apps that uses headers for auth/authorization. This app has no interface, just an API for other SPA apps. 

 I want to provide other devs a nice interface to play with the API with as little ceremony as possible. The idea is that they can run a task in development that will exercise the login code to login them as a certain user and open up graphql-playground with the populated auth headers and the GraphQL endpoint.

**Comment by AmenZhou** [comment]
Really looking forward to this new feature. There is no walkaround so far for non-react playground.

**Comment by wilsongp** [comment]
Had the same need for a project so put in quick PR #825 to get the functionality.

**Comment by siderakis** [comment]
+1

**Comment by wilsongp** [comment]
@timsuchanek What are the odds of this getting pulled in? PR is only a few lines and I'm happy to make any changes.

**Comment by Huvik** [comment]
Thanks to @wilsongp its done in #825 and will be released in the new version of the playground.
