### ISSUE TITLE
Better error visibility in the variables and headers editors

### ISSUE THREAD

**Issue by lukejagodzinski** [prisma/graphql-playground#718]
Currently, it's very hard to notice an error in the dark theme in the variables/headers editor. When there is for example a trailing comma, then it will only underline the `}` character which is barely visible as I've showed in the included screenshot. I have 4K monitor and it makes it even harder to notice. And the error in the result panel is not descriptive enough.

#### This issue pertains to the following package(s):

- [x] GraphQL Playground
- [x] GraphQL Playground Lambda Middleware

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.6.7

#### What is the expected behavior?

Better error visibility like for example red dot next to the line number?

#### What is the actual behavior?

Underlined `}` character which is barely visible especially in the dark them.

#### What steps may we take to reproduce the behavior?

Introduce typo in the variables or headers editor like for example trailing comma

<img width="1920" alt="screen shot 2018-06-01 at 2 42 16 pm" src="https://user-images.githubusercontent.com/1051229/40841236-0f22908a-65aa-11e8-8b52-e140ea83aee8.png">

**Comment by Huvik** [comment]
There is new errors linting in the new release. 🚀
