### ISSUE TITLE
Cookies are not being sent in Playground Express

### ISSUE THREAD

**Issue by alex996** [prisma/graphql-playground#748]
#### This issue pertains to the following package(s):
- [x] GraphQL Playground Express Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Ubuntu 16.04.4 LTS xenial

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.0

#### What is the expected behavior?
It should send browser cookies along with the GraphQL request.

#### What is the actual behavior?
The cookies are absent in the request originating from Playground.

#### What steps may we take to reproduce the behavior?
You can reproduce it with a demo app on [glitch](https://glitch.com/edit/#!/opalescent-apparel?path=server.js:11:19)

1. Open the app to land at `/`, a cookie is set
2. Navigate to `/graphql` and run a query `{ hello }`
3. Observe the browser console and/or glitch console

![req](https://user-images.githubusercontent.com/15240969/41795332-5702aeb2-7630-11e8-9aaa-996ab3ad5183.png)

You can see that **Cookie** is missing from **Request Headers** even though it is set in the browser

![cookie](https://user-images.githubusercontent.com/15240969/41795503-fee37c42-7630-11e8-9e78-dbbb513049cf.png)

The cookie is hence not sent over to express

![log](https://user-images.githubusercontent.com/15240969/41795366-768f6144-7630-11e8-9735-916ef5290589.png)

Note that the demo app runs on Apollo Server v2 which uses `apollo-server-express` version `1.7.0` under the hood. I took the following screenshot from twitch terminal, inside `node_modules`

![version](https://user-images.githubusercontent.com/15240969/41795412-a55061c2-7630-11e8-8052-666a4e47507a.png)

**Comment by alex996** [comment]
With further searching, I found that the cookies can be turned on in settings. But is there a way to pass those options in Node? It's also complicated by the fact that I am using the playground behind Apollo Server.

**Comment by oxyno-zeta** [comment]
I have the same problem.
I've tried this but it is not working.

```javascript
app.get('/graphiql', expressGraphqlPlayground({
        endpoint: '/graphql',
        settings: {
            'request.credentials': 'include',
        },
    }));
```
If you have an idea !

Thanks !

**Comment by gustavlrsn** [comment]
Also using playground behind Apollo Server and having the same issue.

**Comment by tanekim77** [comment]
Yes, I confirmed that this is still an issue.

**Comment by frederikhors** [comment]
Yes, still an issue today, with `apollo-server` I'm using this without success:

```js
const serverApollo = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ req }) => {
    return {...code...};
  }
  playground: {
    settings: {
      "request.credentials": "include"
    }
  }
});
```

**It doesn't work!**

**Comment by Josaber** [comment]
I am using this:

```
  playground: {
    settings: {
      'editor.theme': 'light',
      'editor.cursorShape': 'block',
      'request.credentials': 'same-origin'
    }
  }
```

It still doesn't work.

**Comment by vladanpaunovic** [comment]
I am using
```
'request.credentials': 'same-origin',
```
But still, the issue is there. Cookies are not being set.

**Comment by vladanpaunovic** [comment]
Here is what I found as a workaround:

1. Go to your GraphQl Playground
2. In the top right corner click on the gear icon (settings)

3. Change the following
```diff
{
-  "request.credentials": "omit",
+  "request.credentials": "same-origin",
}
```

Somehow, **the client is not using the server settings**, therefore it consumes `request.credentials: "omit"` instead of `"same-origin"`

**Comment by Josaber** [comment]
@vladanpaunovic Yes, we use this too.

**Comment by curry684** [comment]
That's not so much a workaround as the actual bug - the default user settings are always "omit" instead of the serverside defined default.

**Comment by vincenzo** [comment]
I am trying to collect all these 'settings' issues in one place; I think it's beneficial that all of them are taken into consideration at once, lest we end up with partial fixes or fixes that break other stuff. 

Here's the place: https://github.com/prisma/graphql-playground/issues/826

Could you all have a look and confirm the problem in this present issue has been captured in the one above?

**Comment by manjula91** [comment]
Is 'include' linked to boolean value false? Seems like because in my case both of the code works

```
playground: {
    settings: {
      'request.credentials': false,
    }
  }

```

```
playground: {
    settings: {
      'request.credentials': 'include',
    }
  }

```

**Comment by Fxlr8** [comment]
Oh my god, I wasted so much time on this problem!

**Comment by mcouthon** [comment]
I was having what seemed like CORS issues with apollo-server behind OIDC authentication (Okta), and this was _killing_ me. Thank you @vladanpaunovic !!!

**Comment by TheUniqueMathemagician** [comment]
Hi guys, using Apollo-server-express, I also got issue where the cookie wasn't sent with playground.

After some trials an errors I found this solution that worked for me. Hope it helps someone.
``` ts
ApolloServerPluginLandingPageGraphQLPlayground({
    settings: {
        "request.credentials": "include",
        "editor.reuseHeaders": false,
    }
})
```

**Comment by kelvinbush** [comment]
> Here is what I found as a workaround:
> 
> 1. Go to your GraphQl Playground
> 2. In the top right corner click on the gear icon (settings)
> 3. Change the following
> 
> ```diff
> {
> -  "request.credentials": "omit",
> +  "request.credentials": "same-origin",
> }
> ```
> 
> Somehow, **the client is not using the server settings**, therefore it consumes `request.credentials: "omit"` instead of `"same-origin"`

This works fine.Thank you

**Comment by acao** [comment]
For reference, the apollo fork of playground lives here:

https://github.com/apollographql/graphql-playground

If you have any issues with apollo server‘s fork of playground, you can visit apollo‘s spectrum support chat!

**Comment by onadebi** [comment]
I encountered this issue and after trying much of what has already been highlighted here, none still worked for me.
However, after digging further, I realized that when running on your localhost. The **secure** property of your cookie object should always be set to **false** The below code snippet from my express app solved it for me.

```
app.use(
    session({
        store: new RedisStore({ client: redisClient}),
        name: 'qid',
        secret: 'superdupersecret',
        resave: false,
        saveUninitialized: false,
        cookie: {
            httpOnly: true,
            secure: false,
            maxAge: 1000 * 60 * 60 * 24 * 365
        }
    })
);
```

**Comment by Connorapple** [comment]
With Apollo studio not having the ability to change the settings for request.credentials, I found that adding the following settings to the cookie will make the cookie pass and stop returning undefined data:

httpOnly, secure, and SameSite:none

<img width="1169" alt="Screen Shot 2022-11-07 at 5 45 58 PM" src="https://user-images.githubusercontent.com/7513894/200431478-1af719c2-465c-4ec5-8edd-912f717004ac.png">
