### ISSUE TITLE
calling next() after res.end() leads to [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client.

### ISSUE THREAD

**Issue by DanlanNZ** [prisma/graphql-playground#752]
current workaround is to check for `res.finished` in the following request handlers.
Is this functionality ever desired after the response stream has ended?

https://github.com/prismagraphql/graphql-playground/blob/62ecfdb658935a11391701835d15c66a06be68ad/packages/graphql-playground-middleware-express/src/index.ts#L27-L33

**Comment by cucina-md** [comment]
Are there any updates?
It can be easily fixed...

**Comment by andrefilimono** [comment]
Are there any updates?
This issue can be easily fixed ...
