### ISSUE TITLE
graphqlbin share function does not function

### ISSUE THREAD

**Issue by gajus** [prisma/graphql-playground#793]
Attempting to use https://www.graphqlbin.com/v2/new share function produces an error:

```json
{
  "data": {
    "addSession": null
  },
  "errors": [
    {
      "code": 5008,
      "locations": [
        {
          "column": 11,
          "line": 3
        }
      ],
      "message": "software.amazon.awssdk.services.lambda.model.ResourceNotFoundException: Function not found: arn:aws:lambda:eu-west-1:484631947980:function:cj81hi46q03c30196uxaswrz2-add-session (Service: null; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 66711723-89ea-11e8-a743-ab4f35b737a4)",
      "path": [
        "addSession"
      ],
      "requestId": "eu-west-1:simple:cjjpzysua1kz9013124ybf6lu"
    }
  ]
}

```

**Comment by gajus** [comment]
ping @timsuchanek

**Comment by GeorgioWan** [comment]
Same issue 🤔

**Comment by jjdiezm** [comment]
Same issue for us, the legacy URL with any endpoint (https://legacy.graphqlbin.com/... 6chars) is redirecting us to https://legacy.graphqlbin.com/new requiring an end point.

**Comment by mkochendorfer** [comment]
Also seeing this issue.  It also appears that the Share button fails with an error in the console:
```
Cannot read property 'id' of null
```

**Comment by mkochendorfer** [comment]
I am also seeing the issue for Apollo Server 2 projects on Glitch like https://apollo-launchpad.glitch.me/

**Comment by mkochendorfer** [comment]
Just tested this on a local project using the HAPI middleware, and it is failing there as well.

**Comment by wKovacs64** [comment]
Another version of the console error (for people Googling):

```
TypeError: "n.data.addSession is null"
```

Looks like it's coming from here: https://github.com/prisma/graphql-playground/blob/524155be1d944c6c564fff9cbdfcfd7980cf9ece/packages/graphql-playground-react/src/state/sharing/sharingSaga.ts#L34

**Comment by konsumer** [comment]
Looks like a missing lambda:```{
  "data": {
    "addSession": null
  },
  "errors": [
    {
      "locations": [
        {
          "line": 3,
          "column": 11
        }
      ],
      "path": [
        "addSession"
      ],
      "code": 5008,
      "message": "software.amazon.awssdk.services.lambda.model.ResourceNotFoundException: Function not found: arn:aws:lambda:eu-west-1:484631947980:function:cj81hi46q03c30196uxaswrz2-add-session (Service: null; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: 7e97f93b-c68c-11e8-b263-13c33c672168)",
      "requestId": "eu-west-1:simple:cjms952td19st0108a7jc99qg"
    }
  ]
}```

**Comment by konsumer** [comment]
Looks like this would resolve it: #847

**Comment by konsumer** [comment]
But maybe not. When I go to the [playground for the share-server](https://api.graphqlbin.com/) and copy in the query, I get a `Bad Gateway` error.

**Comment by Huvik** [comment]
Graphqlbin now works properly, sorry for troubles. Enjoy using it now

**Comment by mkochendorfer** [comment]
@Huvik Can you elaborate on what the fix was?  Because I am still seeing this being broken on other systems using GraphQL Playground.  Like https://apollo-launchpad.glitch.me/

**Comment by mkochendorfer** [comment]
https://api.graphqlbin.com/ is also still broken

**Comment by mkochendorfer** [comment]
Looks like the fix is in https://github.com/prisma/graphql-playground/pull/847/files

**Comment by marceloverdijk** [comment]
Other systems (like https://apollo-launchpad.glitch.me/ and https://api.graphqlbin.com/) embedding the Playground are probably using jsDelivr like inlcuding:

```
<script src="//cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js"></script>
```

But jsDelivr does not contain `v1.8.0`, only up to `v1.7.8`, see https://www.jsdelivr.com/package/npm/graphql-playground-react

This is similar issue as https://github.com/prisma/graphql-playground/issues/865

**Comment by Huvik** [comment]
`1.7.8` its correct version of react playground. Electron version is `1.8.0` and has react playground version `1.7.8` inside :)

**Comment by marceloverdijk** [comment]
OK than I'm really interested to see why #865 is happening, as I can't understand.

**Comment by Huvik** [comment]
I will look into it next week :)
