### ISSUE TITLE
Possible NPM Registry publish issue

### ISSUE THREAD

**Issue by sethvoltz** [prisma/graphql-playground#807]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

macOS Sierra and Linux VM

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

@apollographql/graphql-playground-html^1.6.0

#### What is the expected behavior?

The package installs

#### What is the actual behavior?

Error response `not_found` when running through yarnpkg or our internal Artifactory

#### What steps may we take to reproduce the behavior?

- This is all I'm running over here, however we go through Artifactory: `yarn add @apollographql/graphql-playground-html`
- Removing `~/.npmrc`, it attempts to hit yarnpkg and that also errors
- Specifying `registry.npmjs.org` in a new `~/.npmrc` it hits that server, still errors
- Checking `registry.npmjs.org` directly it looks like the package isn't aliased or deployed fully:

```
$ curl -s 'https://registry.npmjs.org/@apollographql/graphql-playground-html' | head -c 100
{"error":"Not found"}%
$ curl -s 'https://registry.npmjs.org/@apollographql%2fgraphql-playground-html' | head -c 100
{"_id":"@apollographql/graphql-playground-html","_rev":"4-db82291198ebf269e1c1d3cfc2116326","name":"%
```

It would seem the registry norm is to respond to both. I tested on a handful of namespaced packages we use, e.g.

```
$ curl -s 'https://registry.npmjs.org/@types/node' | head -c 100
{"_id":"@types/node","_rev":"1590-43dd788ac349c6b3d47bea085bc29fc0","name":"@types/node","descriptio%
$ curl -s 'https://registry.npmjs.org/@types%2fnode' | head -c 100
{"_id":"@types/node","_rev":"1590-43dd788ac349c6b3d47bea085bc29fc0","name":"@types/node","descriptio%
```

_Please provide a gif or image of the issue for a quicker response/fix._

![image](https://user-images.githubusercontent.com/39506/43667794-6e798da8-972e-11e8-9084-3e602487f5b7.png)

**Comment by digitalgears** [comment]
Im seeing the exact same issue. Is there a work around for this?

**Comment by digitalgears** [comment]
ok. I fixed this by changing the npm registry from .org to .com

`npm set registry https://registry.npmjs.com`

**Comment by sethvoltz** [comment]
@digitalgears do you know if this is a deliberate change by NPM or possibly the .org mirror has some corruption?

**Comment by digitalgears** [comment]
I'm not sure to be honest. My guess would be the latter.

**Comment by Huvik** [comment]
This is a fork from Apollo, we don't have any control about it, but they will in future add back this package to server.
