### ISSUE TITLE
Subscriptions now working in GraphQL Playground Express Middleware 1.7.2

### ISSUE THREAD

**Issue by MoonTahoe** [prisma/graphql-playground#808]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [x] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
mac High Sierra 10.13.6

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.2

#### What is the expected behavior?
The Expected behaviour works on [graphqlbin.com](https://www.graphqlbin.com), and with the GraphQL Playground Electron app. 

1. When I send a Subscription Operation
2. The `subscribe` resolver should be invoked
3. Subscriptions should work

#### What is the actual behavior?
1. When I send a Subscription Operation
2. The `subscribe` resolver is not invoked
3. Subscriptions do not work

I had to rool all the way back to __1.5.7__ to make the subscriptions work. They expected behavior works in this version, but not in the current release.

#### What steps may we take to reproduce the behavior?
1. Setup an Apollo Server 2.0 with express
2. Use the graphql-playgound-middleware-express@1.7.2
3. Add Subscription types and resolvers
4. Add a `console.log` to the `subscribe` resolver for any subscription
5. Start the app, navigate to the playground
6. Insert a subscription and subscribe
7. You will not see you comment.

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by Huvik** [comment]
@MoonTahoe could you please provide minimal repo example? I will then fix it, thx!

**Comment by Huvik** [comment]
I just tested it, and everything works if its still problem please reopen the issue.
