### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by mikeerickson** [prisma/graphql-playground#814]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

I am curious if this project is maintained (there are a large number of open issues)  

if so, I would be happy to report my issues (using the Electron app version) and see what you think about them.

**Comment by timsuchanek** [comment]
@mikeerickson thanks for asking this! Yes, this project is maintained!
We didn't have the resources in the last couple of weeks to spend a lot of time on the project, but will do so in the coming weeks.

So please post your electron issues, they won't be forgotten!

**Comment by Huvik** [comment]
We released a new version of electron version a few days back.
