### ISSUE TITLE
Can't see comments from typeDefs in Playground

### ISSUE THREAD

**Issue by apollomusa** [prisma/graphql-playground#819]
Here an example of my typeDef

```
const typeDefs = gql`
  # Comments in GraphQL are defined with the hash (#) symbol.

  # This "Book" type can be used in other type declarations.
  type Book {
    title: String
    author: String
  }

  # The "Query" type is the root of all GraphQL queries.
  # (A "Mutation" type will be covered later on.)
  type Query {
    books: [Book]
  }
`;
```

But in the Playground, I am not seeing the comments displaying: 

![screen shot 2018-08-16 at 4 54 47 pm](https://user-images.githubusercontent.com/34455928/44234647-19bf1980-a175-11e8-8612-33f753f97de1.png)

**Comment by crapthings** [comment]
yes where are comments ?

**Comment by crapthings** [comment]
ok it looks like new syntax is just "this is a comment"

**Comment by alan345** [comment]
Both 
`"this is a comment"`
and 
`"""
Comments in GraphQL are defined with the hash (#) symbol.
"""` are not working..

**Comment by Huvik** [comment]
I was just testing comments and `"""` works normally.

**Comment by alan345** [comment]
@Huvik 
Here you have my schema:
```
"I am an ApiKey "
type ApiKey {
  id: ID! @unique
  testMode: Boolean!
  apiKeyEncrypted: String!
  apiKeyLastsChars: String
  domainName: String
  user: User! @relation(name: "ApKeysCascade")
}

"""
I am Porduct Request
"""
type ProductRequest {
  id: ID! @unique
  sellerName: String! @unique
  sellerWebsite: String!
  userRequests: [UserRequest!]!
    @relation(name: "ProductRequestCascade", onDelete: CASCADE)
}
```

and we cannot see them in the playground in `type details`:
![image](https://user-images.githubusercontent.com/15246526/50465003-32bcb000-0949-11e9-9a08-7d34e7b99be0.png)

![image](https://user-images.githubusercontent.com/15246526/50465011-45cf8000-0949-11e9-80ce-532764ac8e93.png)


Thanks

**Comment by alan345** [comment]
I got it! It is because I'm writing the comments in the datamodel, not in the schema. This leads to a new question: how can we imports comments in the generated file? (to be also, in fine, used in the schema)

Same question asked here: https://www.prisma.io/forum/t/getting-prisma-comments-descriptions-to-appear-in-graphql-playground-schema/2980
