### ISSUE TITLE
Not Found: @apollographql/graphql-playground-html@1.6.0

### ISSUE THREAD

**Issue by hansiemithun** [prisma/graphql-playground#823]
Trying to install, but unfortunately throwing error as such

**Comment by akozlov75** [comment]
error Couldn't find package "@apollographql/graphql-playground-html@^1.6.0" required by "apollo-server-express@2.0.6" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by Huvik** [comment]
You are installing fork from apollo. You should ask apollo guys what is going on. But it soon they should start using this package again. Sorry for troubles.
