### ISSUE TITLE
Globally injected !important styles breaks GraphiQL codemirror autocomplete

### ISSUE THREAD

**Issue by arush** [prisma/graphql-playground#828]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
all

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.4

#### What is the expected behavior?
stylesheet should only be added to the <head> when the react component is present on the page

#### What is the actual behavior?
Playground's stylesheet pollutes the global css namespace with styles that affect facebook's actual GraphiQL editor so both cannot be present in same app

#### What steps may we take to reproduce the behavior?
create a react app with Playground on one page and GraphiQL on another

_Please provide a gif or image of the issue for a quicker response/fix._

====

@Huvik 
This use of "!important" is responsible for breaking the normal autocomplete in GraphiQL. There is no way for a developer to fix this since !important takes precedence and we'd have to fork GraphiQL to make it use !important in its inline styling.

**Comment by Huvik** [comment]
We are not overriding any styles from GraphiQL and only `!important` is with default styling of `CodeMirror`. So if you have still a problem please provide small demo repo. Thanks
