### ISSUE TITLE
invisible text in the error tooltip

### ISSUE THREAD

**Issue by lidorcg** [prisma/graphql-playground#832]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

 - OS: `Ubuntu 18.04`
 - `prisma` CLI: [`prisma/1.15.3 (linux-x64) node-v10.9.0`]
- Browser: firefox quantum 62.0 (64-bit) for ubuntu

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.7.2

#### What is the expected behavior?
The error text on the tooltip should be visible

#### What is the actual behavior?
The tooltip appears but the text is invisible.
When I'm cssing its color to black it appears.

#### What steps may we take to reproduce the behavior?
1. open the playground with firefox
2. write an errorsome query
3. point the pointer to the error

_Please provide a gif or image of the issue for a quicker response/fix._

![transperant-text-bug](https://user-images.githubusercontent.com/11412645/45181503-538cb880-b227-11e8-98ed-f556d1a1ed63.jpg)

**Comment by floross** [comment]
I got the same error with my local computer

**What OS and OS version are you experiencing the issue(s) on?**

    OS: Archlinux
    Browser: firefox quantum 62.0 (64-bit) for ubuntu

**Comment by cailloumajor** [comment]
Same issue here.
#### What OS and OS version are you experiencing the issue(s) on?
* OS: Debian buster (testing)
* Browser:  Firefox 62.0 (64-bit) & 63.0b8 (64 bits)
