### ISSUE TITLE
Present error information in a clearer way

### ISSUE THREAD

**Issue by do4gr** [prisma/graphql-playground#835]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac Os with Safari

#### What is the expected behavior?
If a query contains an invalid field (in the screenshot one that does not exist) it should be highlighted.

#### What is the actual behavior?
Just the opening brace at the beginning of the query is underlined. One has to read the error message to figure out what exactly is wrong with the query.

#### What steps may we take to reproduce the behavior?
<img width="782" alt="bildschirmfoto 2018-09-10 um 15 48 32" src="https://user-images.githubusercontent.com/16278407/45301447-461a4b80-b511-11e8-8671-b23db06719c3.png">

**Comment by Huvik** [comment]
Fixed in the new release.
