### ISSUE TITLE
Clicking the share button in share playground does nothing

### ISSUE THREAD

**Issue by appsolutegeek** [prisma/graphql-playground#838]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MAC OS X High Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.0

#### What is the expected behavior?

I presume something should open in the browser or at least show the URL

#### What is the actual behavior?

Does nothing clicking on the share button

#### What steps may we take to reproduce the behavior?

On an active tab, click share playground and then click share

_Please provide a gif or image of the issue for a quicker response/fix._
![image](https://user-images.githubusercontent.com/2370364/45593836-15ae3380-b98f-11e8-8b04-07f26c30fe07.png)

**Comment by borisowsky** [comment]
To addition:
![image](https://user-images.githubusercontent.com/14042959/45690813-8142fd00-bb57-11e8-900b-9d50441f6587.png)

**Comment by gwardwell** [comment]
I'm seeing the same issue and exact same error message as @borisowsky when running `apollo-server-koa` and `graphql-playground`.

**Comment by alexanderlamb** [comment]
same here in browser and MAC OS X High Sierra

**Comment by ekristen** [comment]
Same issue for HTML version, 1.6.0, Chrome/Safari/Firefox

**Comment by Huvik** [comment]
What version of `graphql-playground` are you using? It's visible if you click on settings cogwheel on right side bottom corner. Thx for response, but it should work right now

**Comment by mportela** [comment]
1.7.4
same here...

**Comment by nathanchapman** [comment]
@Huvik this has not been resolved in the latest version of `graphql-playground-html`

```
npm ls @apollographql/graphql-playground-html
project
└─┬ apollo-server-hapi@2.1.0
  └── @apollographql/graphql-playground-html@1.6.4
```

```
TypeError: Cannot read property 'id' of null
    at sharingSaga.ts:34
    at r (middleware.js:105500)
    at Object.next (middleware.js:105466)
    at h (proc.js:311)
    at n (proc.js:388)
```

Please reopen.

**Comment by Huvik** [comment]
Can you try to clear local storage? It will remove history and state of the playground.

**Comment by nvhai245** [comment]
It's been 2 years guys, any update on this?

**Comment by djkgamc** [comment]
lmao

**Comment by acao** [comment]
there is a link on the readme that explains we are merging efforts with graphiql

https://github.com/graphql/graphql-playground/issues/1366#issuecomment-1062088978

there are already graphiql plugins for this!

**Comment by djkgamc** [comment]
Got it! the quick fix for this repo would be to remove the Share button though, if it doesn't do anything
