### ISSUE TITLE
"request.credentials": "include" does not allow sending Cookie header

### ISSUE THREAD

**Issue by thedude42** [prisma/graphql-playground#839]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOS 10.13.6

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.0 (homebrew)

#### What is the expected behavior?
When I update the settings to include property `"request.credentials": "include"` and I set an HTTP header in the UI like

```
{
  "Cookie":"xxxx" 
}
```

I expect to see the Graphql Playground app transmit the Cookie header in the requests it sends.

#### What is the actual behavior?
No Cookie header is sent regardless of the presence of the above configuration

#### What steps may we take to reproduce the behavior?
- change settings in the Graphql Playground electron app to include `"request.credentials": "include"`
- set a Cookie header in the "HTTP Headers" pane:

```
{
  "Cookie":"xxxx" 
}
```

- Send a query and observe (eiter logging from the graphql endpoint or on the wire via traffic capture) that no Cookie header is being sent.
- Change the name of the cookie header, e.g. "Cookie123" and repeat the test, and observe the header is now transmitted as expected.

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by Huvik** [comment]
This should work in the latest version, sorry for problems. If its still problem reopen please.

**Comment by jirikrepl** [comment]
Hello,
in what version should this be fixed, please? 

I see exactly the same behavior on mac with version 1.8.10 (1.8.10.5129)

header with name `cookie` is is filtered in request from GraphQL Playground.
From my frontend request, I have `cookie` header set correctly

**Comment by lnwu** [comment]
Any update on this?

**Comment by johannessteu** [comment]
I also got it on 1.8.10.  Any chance to reopen this one @thedude42 @huv1k ?

**Comment by janithkv** [comment]
Same here

**Comment by axos88** [comment]
Same here.

**Comment by tylerstar** [comment]
Same here

**Comment by cotterjd** [comment]
Same here

**Comment by javedbartlett** [comment]
Same here

**Comment by javedbartlett** [comment]
Same here.
