### ISSUE TITLE
Can you query an AWS AppSync API from GraphQL PlayGround?

### ISSUE THREAD

**Issue by adrianwe** [prisma/graphql-playground#840]
Hey guys,

I would love to use the Playground for test queries and such. Any experience in setting this up? AWS AppSync gives you a config file in the following format, but I suspect this is wired to AWS's Apollo Client and probably not something you can use as a generic URL endpoint with Playground:

```
export default {
    "graphqlEndpoint": "https://12345.appsync-api.region-code.amazonaws.com/graphql",
    "region": "region-code",
    "authenticationType": "API_KEY",
    "apiKey": "12345"
}
```

When you try to enter the endpoint, you get the following error message:

```
{
  "error": "Response not successful: Received status code 401"
}
```

I tried to paste parts of the config file to the HTTP headers, but that didn't help either (no idea how to format that though). Any ideas?

**Comment by 0xdevalias** [comment]
Looking a the AWS AppSync docs for API_KEY, you pass the key in a header called `x-api-key`:
* https://docs.aws.amazon.com/appsync/latest/devguide/security.html#api-key-authorization

Using the 'Http Headers' section of GraphQL Playground, it appears it wants the headers as a JSON object:

```json
{
  "x-api-key": "da2-FOOMYKEY"
}
```

This seemed to allow me to successfully query my API.

**Comment by adrianwe** [comment]
Awesome! That works for me, too. Thank you! 👍

**Comment by dancomanlive** [comment]
How about AMAZON_COGNITO_USER_POOL ?
