### ISSUE TITLE
Question: Where do I enter a GraphQL WebSocket URL (which is different from the /graphql endpoint)?

### ISSUE THREAD

**Issue by debajit** [prisma/graphql-playground#843]
I'm using a GraphQL server (AWS AppSync) that has a completely different WebSocket endpoint than the main /graphql endpoint. I am able to run queries and mutations successfully but not subscriptions. 

How do I let GraphQL-Playground know about the custom Websocket Endpoint?

#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

macOS High Sierra

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.7.0

**Comment by Huvik** [comment]
Pass it like props to playground or have it inside config :) https://github.com/prisma/graphql-config#specifying-endpoint-info
