### ISSUE TITLE
Executing selected query in Graphql-playground.

### ISSUE THREAD

**Issue by phuongthuan** [prisma/graphql-playground#854]
Firstly, thank for the awesome IDE.

But one thing that I'm finding is executing the selected query in Graphql-playground ?

Let's say in one tab, we have a lot of queries. Each time I execute a query, I have to comment on other queries to make sure the IDE can run.

![screen shot 2018-10-12 at 8 50 43 am](https://user-images.githubusercontent.com/20045189/46843353-8fa1d300-cdfc-11e8-9e76-8e0337eed5ed.png)

It would be great if we can execute the query that we have selected. Something like MS SQL Server. Is this possible?

**Comment by Huvik** [comment]
You can do this by naming query and then selecting that query:
![](https://i.imgur.com/MhGMUP3.png)

**Comment by phuongthuan** [comment]
@Huvik Thank you

**Comment by swatipatil-webonise** [comment]
Hello guys,
I want to know if we are running multiple queries in playground, Is there any way to find out number of graphql queries and which queries are there in queue inside our java backend app? Please answer this if anybody knows, thank you.
