### ISSUE TITLE
Many tabs are added, the horizontal scroll bar is not visible.

### ISSUE THREAD

**Issue by keyeMyria** [prisma/graphql-playground#862]
#### This issue pertains to the following package(s):

- [X] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
macos 10.13.6

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.8.0

#### What is the expected behavior?
there are many tabs, the horizontal scrollbar showed.

#### What is the actual behavior?
horizontal scrollbar not show.

#### What steps may we take to reproduce the behavior?
Add many tabs, the latest tab is not visible, and horizontal scroll bar not show.

_Please provide a gif or image of the issue for a quicker response/fix._

![19852112-10c6-4ccc-8ef5-0e0dce7aabb9](https://user-images.githubusercontent.com/3362049/47071401-0a685500-d226-11e8-83b3-106bb027f7ce.png)

**Comment by Huvik** [comment]
For me is still there
![](https://i.imgur.com/2XCJz5R.png)

**Comment by keyeMyria** [comment]
I checked it again, and find that the horizontal scroll bar height is is shorter, color is similar to other zone, and needing mouse moved over the  zone.
Thanks for reply.

**Comment by Huvik** [comment]
Ye, last time scrollbar just broke whole UI look. So we made it minimalistic :)
