### ISSUE TITLE
GraphQL Playground does not show schema documentation but should

### ISSUE THREAD

**Issue by joelgetaction** [prisma/graphql-playground#867]
#### This issue pertains to the following package(s):

- [x ] GraphQL Playground - Electron App
- [x ] GraphQL Playground HTML
- [x ] GraphQL Playground
- [x ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

macOS 10.13.6

#### What is the expected behavior?

latest

#### What is the actual behavior?

Updating my schema with documenation strings either using `#` or `"` or `"""` does not show any documentation in GraphQL Playground, even though GraphiQL and other tools show that documentation just fine.

#### What steps may we take to reproduce the behavior?

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by Huvik** [comment]
Can you provide your schema? Because I was testing it with `"""` and it works normally.

**Comment by alan345** [comment]
Hi @Huvik 
It works with `"""` in file `schema.graphql` but how can you comment something in the file`datamodel.graphql` as file `generated-schema.graphql` is not keeping comments?
(I asked the question here: https://stackoverflow.com/questions/53974926/with-prisma-how-can-we-add-a-comment-for-a-type)
Thanks

**Comment by Huvik** [comment]
So its problem how Prisma generates schema you can read more about it here https://github.com/prisma/prisma/issues/2152

**Comment by alan345** [comment]
yep, thanks! :/ 

Another answer is here: https://www.prisma.io/forum/t/comments-in-prisma-graphql-from-datamodel-graphql/4330/2?u=alan345

`Currently, there’s no easy way to resolve this. This is an open feature request, which you can learn more about here: https://github.com/prisma/prisma/issues/2152`

do you use another tool to generate documentation from `datamodel.graphql`

**Comment by Huvik** [comment]
Depends how do you want to use it. And what part you want do document. And what tools do you use etc. I don't know anything about your stack.

**Comment by alan345** [comment]
I just want to document my GrpahQl types.
Example:
in file `datamodel.graphql`
```
type Product {
  id: ID! @unique
  """
  Url for the product page
  """
  urlName: String! @unique
  """
  List price for the product
  """
  listPrice: Float!
  """
  Trial period in days for the product
  """
}
```
