### ISSUE TITLE
Types sidebar scroll

### ISSUE THREAD

**Issue by Fi1osof** [prisma/graphql-playground#869]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
Ubuntu 18

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.8

#### What is the expected behavior?
Scroll for types sidebar
http://joxi.ru/5mdzNnxckLaBPA

#### What is the actual behavior?
Scroll does not exists
http://joxi.ru/nAyYL6ZSYeanxA

Sidebar hava class overflowAuto, but styles is empty for .overflowAuto;
Set element style overflow: auto fix this problem for me.

#### What steps may we take to reproduce the behavior?

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by effektsvk** [comment]
Can confirm, happens to me on macOS Mojave (10.14) as well. I wouldn't mind it if automatic updates weren't enabled, which every run of the application updates it to the latest (broken) version. Thanks for the workaround @Fi1osof, it works, at least on the levels you override.

**Comment by Huvik** [comment]
You don't need to download update for the latest version. We will fix it next week or if somebody is going to do PR i can merge it.
