### ISSUE TITLE
Vertical scrolling doesn't work in Schema view

### ISSUE THREAD

**Issue by mschipperheyn** [prisma/graphql-playground#883]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac OS

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.8.0

#### What is the expected behavior?
When the schema view contains a lot of children, a vertical scrollbar is needed. 

#### What is the actual behavior?
Overflow is set to hidden, making it impossible to see what is below the visible part of the screen

#### What steps may we take to reproduce the behavior?
A schema with enough children that the size of the page is larger than than the screen

_Please provide a gif or image of the issue for a quicker response/fix._

**Comment by Huvik** [comment]
Sorry for issues, its fixed inside #875. I will release it today so if its still problem after the new version, let me know.
