### ISSUE TITLE
Auto-focus of query editor should be configurable or disabled when Playground is an embedded element

### ISSUE THREAD

**Issue by nikolasburk** [prisma/graphql-playground#884]
The Prisma website uses an embedded version of CodeSandbox which also has a GraphQL Playground, e.g. here: https://www.prisma.io/with-graphql/

When the site loads and the Playground is being displayed, the editor receives auto-focus and thus the page scrolls down. 

It should be possible to disable the auto-focus in the query editor.

**Comment by schickling** [comment]
Ideally the Playground can detected whether it's embedded somewhere and then not apply the auto-focus. Having to explicitly set a `autoFocus: false` property would be suboptimal.
