### ISSUE TITLE
Vertical scrolling doesn't work in all of the columns of Schema in Electron app

### ISSUE THREAD

**Issue by davidrf** [prisma/graphql-playground#885]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOs High Sierra 10.13.6

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.8.2 graphql-playground-electron

#### What is the expected behavior?
When the content of any column of the schema view overflows, a vertical scroll bar appears allowing the user to scroll in order to view all the content in the column.

#### What is the actual behavior?
When the content of any column of the schema view overflows, the content is cut off at the bottom of the column. The only exception is the leftmost column which works as expected.

#### What steps may we take to reproduce the behavior?
View a schema with lots of types and/or resize the window so the app window height is less than the content of a column.

_Please provide a gif or image of the issue for a quicker response/fix._
![screen shot 2018-11-15 at 3 56 12 pm](https://user-images.githubusercontent.com/9678182/48581182-1449aa80-e8ef-11e8-8a92-a47d2d3fd90e.png)
In the image above the leftmost column in the schema view has a grey scroll bar to allow you to scroll to view all the available queries and mutations. However, the middle and rightmost columns in the schema view do not have such a scroll bar. Thus, it is not possible to view all the fields in the middle column or view all the implementations in the rightmost column

Also, there was a previous issue #883 which attempted to fix the same problem, but didn't fix it for all columns in the schema view for the Electron app.

**Comment by effektsvk** [comment]
Today, I've installed a new update and the issue still persists... The `overflow: auto` CSS is still missing and when I add it via Dev Tools it works.

**Comment by Huvik** [comment]
Still problem with safari.

**Comment by kimobrian** [comment]
This is the case for the Desktop app too

**Comment by effektsvk** [comment]
Yay, this update finally fixed it, **for real**. I think the issue can be closed now 🎉
