### ISSUE TITLE
Don't open and focus on new tab when sharing playground

### ISSUE THREAD

**Issue by daxro** [prisma/graphql-playground#893]
#### This issue pertains to the following package(s):

- [ ? ] GraphQL Playground - Electron App
- [ x ] GraphQL Playground HTML
- [ ? ] GraphQL Playground
- [ ? ] GraphQL Playground Express Middleware
- [ ? ] GraphQL Playground Hapi Middleware
- [ ? ] GraphQL Playground Koa Middleware
- [ ? ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Chrome v 70

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
https://www.graphqlbin.com/v2/

#### What is the expected behavior?
Don't open and focus on "New Tab" when sharing playground.

#### What is the actual behavior?
"New Tab" is opened and focused.

#### What steps may we take to reproduce the behavior?
1) Rename "New Tab" and change the query
2) Share playground
3) Go to shared playhround

_Please provide a gif or image of the issue for a quicker response/fix._
Example here: https://graphqlbin.com/v2/yo8yfN

**Comment by lorensr** [comment]
Confirming. Below is how it looks. Prefer the old v1 behavior that did not create a new tab.

When clicking share:

![image](https://user-images.githubusercontent.com/251288/49877988-e6d91980-fe26-11e8-84d9-4717fa241d1e.png)

When visiting link:

![image](https://user-images.githubusercontent.com/251288/49878017-f8222600-fe26-11e8-8b0f-1d4f7bf0909f.png)

**Comment by zhammer** [comment]
@Huvik is this an intentional change?

**Comment by zhammer** [comment]
it seems like the new tab is a side effect of `INJECT_HEADERS`. skipping`INJECT_HEADERS` in redux devtools when on a shared workspace doesn't create a new tab / keeps focus on initial tab.

![graphql-playground-redux-history](https://user-images.githubusercontent.com/6956487/50114628-fd121b80-0212-11e9-9f7d-3b32c8d6b0c4.png)

**Comment by zhammer** [comment]
comes from:
https://github.com/prisma/graphql-playground/blob/648dddffc6f3d08a6a2dd040b558c196be406206/packages/graphql-playground-react/src/state/sessions/reducers.ts#L446-L476

i can look into fixes later in my free time

**Comment by zhammer** [comment]
outside of this change fixing the issue for shared playgrounds without injected headers, it seems like this logic itself is broken
```diff
  -447,7 +447,7 @@ const reducer = handleActions(
     // it makes sure, that there definitely is a tab open with the correct header
     INJECT_HEADERS: (state, { payload: { headers, endpoint } }) => {
       // if there are no headers to inject, there's nothing to do
-      if (!headers || headers === '') {
+      if (!headers || headers === '' || Object.keys(headers).length === 0) {
         return state
       }
       const headersString =
```
