### ISSUE TITLE
"GraphQL Playground" is damaged and can't be opened.

### ISSUE THREAD

**Issue by lunelson** [prisma/graphql-playground#923]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

[1.8.5 release](https://github.com/prisma/graphql-playground/releases/tag/v1.8.5) on macOS comes through as "damaged". I've tried twice to download it.

![screen shot 2019-01-10 at 11 05 18](https://user-images.githubusercontent.com/1242864/50961344-c6ed5200-14c7-11e9-8592-2b3e4d5cbab0.png)

**Comment by Huvik** [comment]
Hey @lunelson and what version? I just tried it with `dmg` version and it worked fine for me.

**Comment by lunelson** [comment]
Hi @Huvik you're right, the `.dmg` version works fine. It's the `graphql-playground-electron-1.8.5-mac.zip` file, which unzips as damaged (on my system at least).

**Comment by Huvik** [comment]
Thanks, I will look into that :)

**Comment by Huvik** [comment]
Okay, I was just testing it and it works fine. Do you have some special system settings? Or how you extracted it?

**Comment by lunelson** [comment]
Ah yes, it might be due to "The Unarchiver". I didn't really notice it but it seems to have set itself as the default tool to open `.zip` files on my system. Using the macOS "Archive Utility" the zip version seems to work fine. Sorry for the confusion.

**Comment by kepi0809** [comment]
I had similar issues when I download the `zip` file too  (see screenshot), at first didn't even see the dmg file only the zipped one. Must be some issues with the default extractor on mac
<img width="532" alt="image" src="https://user-images.githubusercontent.com/27559347/76426738-bc6c6800-63ab-11ea-9c3f-32c628c94a00.png">

**Comment by cdll** [comment]
i 've tried the `.zip` app(from [www.electronjs.org](https://www.electronjs.org/apps/graphql-playground)) and faced to the issues above, then finding issue here, then i 've tred the `.dmg` one  now but it still not working but only showing a empty black app screen.
![image](https://user-images.githubusercontent.com/8576686/85193421-f3cba880-b2fa-11ea-8ac7-39d346f4d31b.png)

**Comment by lunelson** [comment]
For me the solution was the ZIP version but only unzipped using macOS "Archive Utility"
