### ISSUE TITLE
GraphQL Playground app on MacOS updates 100 times a day

### ISSUE THREAD

**Issue by simPod** [prisma/graphql-playground#926]
This notification comes up like 100 times a day on macos
![image](https://user-images.githubusercontent.com/327717/50999969-02ba0300-152c-11e9-9714-2ac3351b6a15.png)

Does it really download some kind of update or is it just a bug? Thanks!

**Comment by Huvik** [comment]
Thanks for reporting, but its duplication of https://github.com/prisma/graphql-playground/issues/891. I will try to fix it next week.
