### ISSUE TITLE
Pressing the "New Workspace" button doesn't do anything

### ISSUE THREAD

**Issue by vjsingh** [prisma/graphql-playground#929]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Max OSX Mojave, Chrome browser

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
I am running the command via `graphql playground`. I just ran `npm install -g graphql` and now `graphql --v` returns `2.17.0`

#### What steps may we take to reproduce the behavior?
Pressing the "New Workspace" button does nothing

_Please provide a gif or image of the issue for a quicker response/fix._
![playground bug](https://user-images.githubusercontent.com/318312/51121083-856ce780-17e4-11e9-899c-f8d866506070.gif)

**Comment by Huvik** [comment]
Hey, thanks for reporting. This should be visible just in electron version. It's kind of easy to fix.
