### ISSUE TITLE
UI crashing, state lost

### ISSUE THREAD

**Issue by joshhopkins** [prisma/graphql-playground#938]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?

MacOS 10.14.3

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

1.8.5 (1.8.5)

#### What is the expected behavior?

Not to crash.

#### What is the actual behavior?

UI crashing, state lost, workspace lost.

#### What steps may we take to reproduce the behavior?

1. Create new tab with subscription
2. UI displays 'listening'
3. UI will go blank
4. Quite app
5. Workspace gone

_Please provide a gif or image of the issue for a quicker response/fix._

![screen shot 2019-01-25 at 10 57 40 pm](https://user-images.githubusercontent.com/11452674/51775273-772c9e80-20f5-11e9-9beb-9578d4f6efe0.png)

**Comment by Huvik** [comment]
@joshhopkins Could you please share output from developer tools? You can toggle developer console in window menu.

**Comment by joshhopkins** [comment]
@Huvik after updating to 1.8.6 (1.8.6), I'm also seeing the same Uncaught Error as @shawnbierman. Though this is now occurring during startup, so not sure if its related.

**Comment by flowerett** [comment]
With new 1.8.7 update it works for me, but it immediately downloads 1.8.6 as an update and stops working.

**Comment by Huvik** [comment]
Is this still a problem?

**Comment by shawnbierman** [comment]
> Is this still a problem?

Seems to be working with 1.8.7 (1.8.7), and just updated to Version 1.8.9 (1.8.9) and looks good.

**Comment by joshhopkins** [comment]
Haven't experienced this issue with 1.8.9.

**Comment by Huvik** [comment]
Okay, so I am closing this.
