### ISSUE TITLE
[Feature-Request]: integrate with graphql voyage

### ISSUE THREAD

**Issue by KevinYaoooooo** [prisma/graphql-playground#939]
Hey, your tool is awesome, it saves me from the pain.
but I think it's more cooler and convenient if you integrate with [graphql-voyager](https://apis.guru/graphql-voyager/), it allows you to show the graphical tree map, or should I say ability map, it would be a lot easier to see the relationships between the typed-object and much intuitive. I believe it's gonna improve so much DX.

**Comment by Huvik** [comment]
Closing this issue you can check more in #935
