### ISSUE TITLE
Update to 1.8.6 is broken

### ISSUE THREAD

**Issue by flyhigh-hifi** [prisma/graphql-playground#941]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Mac OS 10.14.2

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
 1.8.6

#### What is the expected behavior?
Show select schema url dialog

#### What is the actual behavior?
After update and restart GraphQL playground opens with empty screen 

#### What steps may we take to reproduce the behavior?
Happens after update

_Please provide a gif or image of the issue for a quicker response/fix._
<img width="1200" alt="screenshot 2019-01-27 at 20 55 07" src="https://user-images.githubusercontent.com/29523271/51804788-21cbcb00-2276-11e9-910c-89451d31f09b.png">

**Comment by techniq** [comment]
Same here

**Comment by Huvik** [comment]
Yes, something went wrong with electron build, trying to figure out what is happening. Sorry for troubles, current workaround is to download the old version.

**Comment by mmendez512** [comment]
Happening for me on Windows 10 with the new install for both 1.8.6 and 1.8.5. For now, I'll just use GraphiQL until there's a fix.

**Comment by pitops** [comment]
Reverting to v1.8.5 works but you need to also disable automatic updates as it automatically updates next update hence when you close the app it will go back to v1.8.6. 

Any knows how to disabled updates?

**Comment by Huvik** [comment]
Sorry for troubles, it should be fixed in latest release.
