### ISSUE TITLE
Infinite loop to load the schema

### ISSUE THREAD

**Issue by jeanpfs** [prisma/graphql-playground#944]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [ x ] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
All

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
1.7.10

#### What is the expected behavior?
Send a request to retrieve the schema and wait for the response

#### What is the actual behavior?
The playground is looped through requisitions to refer to the endpoint documentation

#### What steps may we take to reproduce the behavior?
1. Open demo https://www.graphqlbin.com/v2/6RQ6TM
2. See chrome console

_Please provide a gif or image of the issue for a quicker response/fix._
![image](https://user-images.githubusercontent.com/8262794/51840577-9133d000-22f3-11e9-8bd9-926763d02026.png)

**Comment by Huvik** [comment]
@jeanpfs This is a new feature for pooling schema to have better DX, you can disable it in the settings menu.
