### ISSUE TITLE
Polling for schema breaks playground for larger schemas

### ISSUE THREAD

**Issue by divyenduz** [prisma/graphql-playground#947]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [x] GraphQL Playground
- [x] GraphQL Playground Express Middleware
- [x] GraphQL Playground Hapi Middleware
- [x] GraphQL Playground Koa Middleware
- [x] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
MacOS and GraphQL Playground HTML is where I tested this but the issue should affect all versions. 

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
`1.7.17`

#### What is the expected behavior?
Playground should poll for schema only if the previous request is complete. We can also provide polling option as an interval in seconds on place of a boolean. `0` being default and disabled. `n` being `n` seconds polling interval. 

#### What is the actual behavior?
Playground is polling for schema via introspection continuously and for a large enough schema, this is causing the max [connection per hostname](http://www.browserscope.org/?category=network&v=top) to overflow. As a result this stalls the actual query as well. 

#### What steps may we take to reproduce the behavior?
Open playground with a large schema. Try to make a request. 

![image](https://user-images.githubusercontent.com/746482/51901921-ca953a00-23de-11e9-81ec-1173bf034ac0.png)

**Comment by Huvik** [comment]
Should be fixed with #950 🚀
