### ISSUE TITLE
Electron app launches to blank screen even after uninstall

### ISSUE THREAD

**Issue by tonyxiao** [prisma/graphql-playground#949]
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App

#### What OS and OS version are you experiencing the issue(s) on?
macOS 10.13.6 (17G65)

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?

graphql-playground-electron-1.8.6.dmg

#### What is the expected behavior?

App works
#### What is the actual behavior?
App is stuck upon open. Tried uninstalling and installing but did not help. 
![image](https://user-images.githubusercontent.com/696842/51935232-4b8e0a80-23ba-11e9-995d-02c43ea221f0.png)

#### What steps may we take to reproduce the behavior?
Not sure. It's just completely stuck right now

**Comment by pitops** [comment]
@tonyxiao update to 1.8.7 its fixed

**Comment by geirman** [comment]
@pitops I'm having this trouble too. I just ran `brew cask reinstall graphql-playground` and got version 1.8.6. How do I upgrade to 1.8.7?

**Comment by geirman** [comment]
Ok, I think I figured it out. This worked for me...

`$ brew cask upgrade graphql-playground`

**Comment by Huvik** [comment]
This version is broken, how suggested version `1.8.7` is fixed 🚀
