### ISSUE TITLE
Settings is not persisted like tabs or headers 

### ISSUE THREAD

**Issue by ganesshkumar** [prisma/graphql-playground#970]
#### This issue pertains to the following package(s):

- [ ] GraphQL Playground - Electron App
- [ ] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10 Enterprise 

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
I am consuming playground from [dotnot-graphql](https://github.com/graphql-dotnet/graphql-dotnet). Not sure which version they are running. 

#### What is the expected behavior?
When we have multiple tabs inside playground(to write different queiries and mutatuions) closing the playground browser tab and revisiting playground will open all the query/mutataion tabs that we had before. 

The same behavior is observed with HTTP Header that we set. They are being persisted across the sessions from the same browser. 

However, the `Endpoint` and `Subscriptions Endpoint` which are set from the settings menu is not being persisted
![image](https://user-images.githubusercontent.com/2135089/52840166-726c7080-311e-11e9-8b45-be1970051505.png)

#### What is the actual behavior?
Similar to the query/mutation tabs and the headers, the `Endpoint` and `Subscriptions Endpoint` in settngs should also be persisted across sessions. (May be the entire set of settings should be persisted across sessions)

#### What steps may we take to reproduce the behavior?
* Enter multiple queries/mutations in different tabs within playground
* Change the `Endpoint` and `Subscriptions Endpoint` from the settings
* Close the browser tab
* Revisit playground. The query/mutation tabs will be persisted but the `Endpoint` and `Subscriptions Endpoint` will be reset to the intial auto-populated values

**Note**: If you can confirm, if this can be solved at playground level, I can pick it up and work on it.

Edit: typo

**Comment by Huvik** [comment]
@ganesshkumar Sorry, but this version is really old. In new versions, everything works properly. So please update the playground there. Then a version of the playground can be seen inside the settings tab in right bottom corner. I am closing this because it's not a problem with the latest version.
