### ISSUE TITLE
Support basic MacOS commands

### ISSUE THREAD

**Issue by joshhopkins** [prisma/graphql-playground#973]
The Electron app for MacOS should support basic MacOS commands, such as:

- Hide app (Command + H)
- Minimise app (Command + M)
- Tab reordering (Click + Drag)

**Comment by lekterable** [comment]
Hey @joshhopkins , I'm happy to let know that some of those things are supported!
I've added Hide App here - https://github.com/prisma/graphql-playground/pull/969 and minimize was already in place, I think. I agree with the tab reordering tho! That would be really cool.
